---
title: in Code
development: yes
description:
  Weblog of Justin Le, covering his various adventures in programming and
  explorations in the vast worlds of computation physics, and knowledge.
feed: http://feeds.feedburner.com/justinleblogdevelopment
copyright: 2016 Justin Le
author:
  name: Justin Le
  email: justin@jle.im
  rel: https://plus.google.com/107705320197444500140
  facebook: mstksg
  twitter: mstk
  gplus: +JustinLe
  # twitter: 907281
  # gplus: 107705320197444500140
  github: mstksg
  linkedin: lejustin
  keybase: mstksg
  coinbase: mstksg
public-blobs: https://github.com/mstksg/blog/tree/develop
interactive-url: https://www.fpcomplete.com/user/jle/
code-samples: code-samples
host:
  secure: no
  base: home.jle0.com
  port: 4111
developer-apis:
  analytics:
    id: UA-443711-7
    domain: jle0.com
  disqus: justinleblogdevelopment
  facebook: "645245675494525"
  add-this: ra-520df7c304b817b9
  feedburner: justinleblogdevelopment
preferences:
  slug-length: 8
  home-entries: 5
  lede-max: 2
  feed-entries: 15
  sidebar-entries: 5
...
